### ISSUE TITLE
Clearly Esp32 board image

### ISSUE THREAD

**Issue by anhnvme** [Jupsi/logi_z906_wifi#8]
Hello.

Could you take a picture esp32 board more clearly ?

**Comment by anhnvme** [comment]
![image](https://github.com/user-attachments/assets/d9817ef5-1aca-46f3-bd26-f6a07d4166cc)
Hello, thank for your guide, my Z906 now online.
But how can I turn on speaker from Home assistant ?

**Comment by Jupsi** [comment]
Hi, the System cant be turned on by Home Assistant since the Power Up is handled by the Console itself. You can set the Z906 to not auto power off.

**Comment by frostaholic** [comment]
this may not be of any use but my z906 is connected to my TV and a raspberry pi for volumio music server. volumio is connected to home assistant for music and TTS. before this I had to manually turn the inputs over which was impossible to know when there was going to be a notification through TTS.
Now I can just make an automation to do it for me.
```
alias: change logitech input to volumio
description: volumio playing change to input 2
triggers:
  - trigger: state
    entity_id:
      - media_player.volumio
    to: playing
conditions: []
actions:
  - action: select.select_option
    metadata: {}
    data:
      option: Input 2
    target:
      entity_id: select.z906_input
mode: single
```
oh then another automation reversed to flip it back to TV input when TTS finishes or music stops
